# Currently (at PoC stage), the only DB migration tool that is supported is sqitch.org
# This "extended" image is supposed to have many other tools in the future (liqubase, flyway, etc.)
FROM sqitch/sqitch:1.0.0

USER root

# Install dependencies.
RUN apt-get update && apt-get -y install bash jq

WORKDIR /home/dblab
COPY ./bin/dblab ./bin/dblab
RUN mv ./bin/dblab /usr/local/bin/dblab 2> /dev/null

ENTRYPOINT []
CMD ./bin/dblab
