FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

RUN apk upgrade --no-cache \
  && apk add --no-cache ca-certificates tzdata

# create non-root user
RUN adduser -D -u 1000 appuser

WORKDIR /app

COPY ./bin/rds-refresh /usr/local/bin/rds-refresh

USER appuser

ENTRYPOINT ["/usr/local/bin/rds-refresh"]
CMD ["--help"]
