# See Guides to learn how to start a container: https://postgres.ai/docs/how-to-guides/administration/engine-manage

FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

# Install dependencies
RUN apk upgrade --no-cache \
  && apk add --no-cache 'docker-cli~29' zfs lvm2 bash util-linux tzdata

WORKDIR /home/dblab

COPY ./bin/dblab-server ./bin/dblab-server
COPY ./configs/standard ./standard
COPY ./api ./api
COPY ./scripts ./scripts

CMD ./bin/dblab-server
