# See Guides to learn how to start a container: https://postgres.ai/docs/how-to-guides/administration/engine-manage

FROM docker:20.10.24

# Install dependencies.
RUN apk update && apk add zfs=0.8.4-r0 --no-cache --repository=https://dl-cdn.alpinelinux.org/alpine/v3.12/main \
  && apk add --no-cache lvm2 bash util-linux tzdata

WORKDIR /home/dblab

COPY ./bin/dblab-server ./bin/dblab-server
COPY ./configs/standard ./standard
COPY ./api ./api
COPY ./scripts ./scripts

CMD ./bin/dblab-server
