FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

# Install dependencies.
RUN apk upgrade --no-cache \
  && apk add --no-cache bash 'docker-cli~29'

WORKDIR /home/dblab

COPY ./bin/run-ci ./bin/run-ci

CMD ./bin/run-ci
