# See Guides to learn how to start a container: https://postgres.ai/docs/how-to-guides/administration/engine-manage

FROM docker:27.1.1

# Install dependencies
RUN apk update \
  && apk add --no-cache zfs lvm2 bash util-linux tzdata

WORKDIR /home/dblab

COPY ./bin/dblab-server ./bin/dblab-server
COPY ./configs/standard ./standard
COPY ./api ./api
COPY ./scripts ./scripts

CMD ./bin/dblab-server
